version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: uv
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: uv
    directory: /packages/core
    schedule:
      interval: daily
  - package-ecosystem: uv
    directory: /packages/chat
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
