name: CI

on: [push, fork, pull_request, workflow_dispatch]

jobs:
  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crate-ci/typos@master

  check:
    strategy:
      matrix:
        os: [ubuntu, windows, macos]
      fail-fast: false
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          pip install uv --disable-pip-version-check
          uv export --no-hashes | uv pip install -r - --system
      - name: Linting
        run: |
          ruff format --check --diff
          ruff check --diff
      - name: Check typing
        run: npx pyright

  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: [core, chat]
      fail-fast: false
    needs: [check, typos]
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: packages/${{ matrix.dir }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Build packages
        run: |
          pip install uv --disable-pip-version-check
          uv build packages/${{ matrix.dir }}
      - name: Publish to PyPI
        continue-on-error: true
        run: uv publish

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Check formatting
        run: deno fmt --check . !README.md
